title: "Vuepressでポートフォリオ作成ハンズオン"
summary: "Vuepressでポートフォリオ作成ハンズオン"
topics: ["javascript", "vue", "vuepress", "ssg"]
published: false
price: 500 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - intro.md
  - about.md
  - overview.md
  - environment.md
  - start.md
  - composition.md
  - automate.md
  - top.md
  - aboutpage.md
  - embed.md
  - githubpages.md
  - ending.md
